apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    id: nfs-yebyen
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.244.1.4
    path: "/"
