apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    id: my-nfs-volume
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.11.248.141
    path: "/"
